trigger:
- master

pool:
  name: 'Default'

steps:
- task: DownloadBuildArtifacts@0
  displayName: 'Download Docker images artifact'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProjectId)'
    pipeline: 'Salmanjutt79.two-tier-flask-app (2)'  # Replace with the name of your CI pipeline
    buildVersionToDownload: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)/docker-images'
    artifactName: 'docker-images'

- task: DockerCompose@0
  displayName: 'Deploy Docker images'
  inputs:
    action: 'Run services'
    dockerComposeFile: 'docker-compose.yml'
    projectName: 'myapp'
    
    additionalImageTags: 'latest'
    containerRegistryType: 'Container Registry'
    dockerRegistryEndpoint: 'Dockerhub-connection'
    #artifactName: 'docker-images'  # Replace with your Docker registry connection name
